server:
  port: 8077
spring:
  application:
    name: esearch
  config:
    import: optional:file:.env[.properties]
    main:
      allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka


kafka:
  topic: notes
  group: json
  port: ${KAFKA_HOST}:9092

