server:
  port: 8077
spring:
  application:
    name: esearch
  config:
    import: optional:file:.env[.properties]
    main:
      allow-bean-definition-overriding: true

kafka:
  topic: notes
  group: json
  port: ${KAFKA_HOST}:9092

elastic:
  host: ${ELASTIC_HOST}
  port: 9200

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus

