scrape_configs:
  - job_name: 'Prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: [ 'localhost:9090' ]
        labels:
          application: 'Prometheus'
  - job_name: 'Elasticsearch input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:8077']
        labels:
          application: 'Notes microservice'